/**
 * Obsidian-friendly markdown export for cortex memories. One file per
 * memory under ~/.apsolut-cortex/obsidian/memories/, plus a top-level
 * index.md that groups memories by project → category → trust.
 *
 * Karpathy: "the LLM writes and maintains all of the data of the wiki,
 * I rarely touch it directly." Every regenerable file gets a sentinel
 * header so we know not to clobber user edits if we add hash tracking
 * later. For now we always overwrite — users should treat the vault
 * as read-only output.
 *
 * The export is idempotent: calling it twice in a row produces the same
 * files. Memories removed from the DB get their .md files deleted on
 * next export so the vault never diverges from the source of truth.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from "fs";
import { join } from "path";
import type { Client } from "@libsql/client";
import { CORTEX_DIR, type Memory } from "./db.js";

export const OBSIDIAN_DIR = join(CORTEX_DIR, "obsidian");
export const MEMORIES_DIR = join(OBSIDIAN_DIR, "memories");
export const INDEX_PATH = join(OBSIDIAN_DIR, "index.md");

const GENERATED_HEADER =
  "<!-- generated by apsolut-cortex export — do not edit; changes will be overwritten -->";

function isoDate(ms: number): string {
  return new Date(ms).toISOString();
}

function memoryFilename(m: Memory, projectName: string): string {
  // Use a slug of the first ~50 chars of content, prefixed by the short id
  // so files sort stably and IDs are still grep-able. Project name is in
  // frontmatter so we don't need it in the filename.
  const idShort = m.id.slice(0, 8);
  const slug = m.content
    .slice(0, 50)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
  const safe = slug.length > 0 ? slug : "memory";
  return `${idShort}-${safe}.md`;
}

function frontmatter(m: Memory, projectName: string): string {
  const fields: Array<[string, string | number | null]> = [
    ["id", m.id],
    ["project", projectName],
    ["project_id", m.project_id],
    ["tier", m.tier],
    ["category", m.category],
    ["trust", m.trust],
    ["weight", m.weight.toFixed(3)],
    ["used_count", m.used_count],
    ["created_at", isoDate(m.created_at)],
    ["last_used", m.last_used ? isoDate(m.last_used) : null],
    ["source", m.source],
    ["source_session_id", m.source_session_id],
  ];
  const lines = ["---"];
  for (const [k, v] of fields) {
    if (v === null || v === undefined) continue;
    const safeValue = String(v).replace(/"/g, '\\"');
    lines.push(`${k}: "${safeValue}"`);
  }
  lines.push("---");
  return lines.join("\n");
}

function memoryFile(m: Memory, projectName: string): string {
  const wikiProject = `[[${projectName}]]`;
  const wikiCategory = `[[category-${m.category}]]`;
  const bodyParts = [
    frontmatter(m, projectName),
    "",
    GENERATED_HEADER,
    "",
    `# ${m.category} · ${m.tier}`,
    "",
    m.content,
  ];
  if (m.context) {
    bodyParts.push("", "## Context", "", m.context);
  }
  bodyParts.push(
    "",
    "---",
    `Project: ${wikiProject} · Category: ${wikiCategory} · Trust: ${m.trust}`
  );
  return bodyParts.join("\n") + "\n";
}

function indexFile(
  memoriesByProject: Map<string, Memory[]>
): string {
  const lines = [
    "---",
    `generated_at: "${new Date().toISOString()}"`,
    "---",
    "",
    GENERATED_HEADER,
    "",
    "# apsolut-cortex memory vault",
    "",
    `${[...memoriesByProject.values()].reduce((s, ms) => s + ms.length, 0)} memories across ${memoriesByProject.size} project(s).`,
    "",
  ];

  const projectNames = [...memoriesByProject.keys()].sort();
  for (const projectName of projectNames) {
    const memories = memoriesByProject.get(projectName)!;
    lines.push(`## ${projectName} (${memories.length})`, "");

    // Group by category
    const byCategory = new Map<string, Memory[]>();
    for (const m of memories) {
      if (!byCategory.has(m.category)) byCategory.set(m.category, []);
      byCategory.get(m.category)!.push(m);
    }

    for (const category of [...byCategory.keys()].sort()) {
      const ms = byCategory.get(category)!;
      lines.push(`### ${category} (${ms.length})`, "");
      const sorted = ms.sort((a, b) => b.weight - a.weight);
      for (const m of sorted) {
        const fname = memoryFilename(m, projectName);
        const snippet =
          m.content.length > 80
            ? m.content.slice(0, 77) + "..."
            : m.content;
        lines.push(
          `- [[memories/${fname.replace(/\.md$/, "")}|${m.id.slice(0, 8)}]] *(${m.trust}, w=${m.weight.toFixed(2)})* — ${snippet}`
        );
      }
      lines.push("");
    }
  }

  return lines.join("\n") + "\n";
}

export interface ExportResult {
  memories_written: number;
  files_removed: number;
  vault_dir: string;
}

export interface ExportOptions {
  projectIdFilter?: string;
  /** Override target vault directory; defaults to OBSIDIAN_DIR. Used by tests. */
  vaultDir?: string;
}

/**
 * Export every memory in the DB to the Obsidian vault. Returns stats.
 *
 * If `opts.projectIdFilter` is provided, only memories for that project
 * are exported AND memory .md files belonging to other projects are
 * left alone. With no filter, the entire vault is regenerated and
 * orphaned .md files (memories that no longer exist in the DB) are
 * deleted.
 */
export async function exportVault(
  db: Client,
  opts: ExportOptions = {}
): Promise<ExportResult> {
  const vaultDir = opts.vaultDir ?? OBSIDIAN_DIR;
  const memoriesDir = join(vaultDir, "memories");
  const indexPath = join(vaultDir, "index.md");
  const projectIdFilter = opts.projectIdFilter;

  if (!existsSync(vaultDir)) mkdirSync(vaultDir, { recursive: true });
  if (!existsSync(memoriesDir)) mkdirSync(memoriesDir, { recursive: true });

  // Pull memories + their project names
  const projects = await db.execute("SELECT id, name FROM projects");
  const projectName = new Map<string, string>();
  for (const r of projects.rows) {
    projectName.set(r.id as string, (r.name as string) ?? "unknown");
  }

  const sql = projectIdFilter
    ? "SELECT * FROM memories WHERE project_id = ?"
    : "SELECT * FROM memories";
  const args = projectIdFilter ? [projectIdFilter] : [];
  const result = await db.execute({ sql, args });

  const memories: Memory[] = result.rows.map((r) => ({
    id: r.id as string,
    project_id: r.project_id as string,
    tier: r.tier as Memory["tier"],
    category: r.category as Memory["category"],
    trust: r.trust as Memory["trust"],
    content: r.content as string,
    context: r.context as string | null,
    source: r.source as string,
    embedding: r.embedding as ArrayBuffer | null,
    weight: r.weight as number,
    used_count: r.used_count as number,
    last_used: r.last_used as number | null,
    created_at: r.created_at as number,
    session_id: r.session_id as string | null,
    flagged: r.flagged as number,
    flag_reason: r.flag_reason as string | null,
    source_session_id: (r.source_session_id as string | null) ?? null,
    source_start_msg_idx: (r.source_start_msg_idx as number | null) ?? null,
    source_end_msg_idx: (r.source_end_msg_idx as number | null) ?? null,
  }));

  // Write one file per memory
  const wantedFiles = new Set<string>();
  const byProject = new Map<string, Memory[]>();

  for (const m of memories) {
    const pName = projectName.get(m.project_id) ?? "unknown";
    if (!byProject.has(pName)) byProject.set(pName, []);
    byProject.get(pName)!.push(m);

    const fname = memoryFilename(m, pName);
    wantedFiles.add(fname);
    writeFileSync(join(memoriesDir, fname), memoryFile(m, pName));
  }

  // Garbage collect orphan files when we exported everything
  let removed = 0;
  if (!projectIdFilter) {
    const present = readdirSync(memoriesDir).filter((f) => f.endsWith(".md"));
    for (const f of present) {
      if (!wantedFiles.has(f)) {
        try { unlinkSync(join(memoriesDir, f)); removed++; } catch {}
      }
    }
  }

  // Index — always regenerated based on the full byProject view
  writeFileSync(indexPath, indexFile(byProject));

  return {
    memories_written: memories.length,
    files_removed: removed,
    vault_dir: vaultDir,
  };
}
